data:
  csv_path: POWER_Point_Hourly_20150101_20250101_033d22N_122d43E_UTC.csv
  skiprows: 15

  ghi_col: ALLSKY_SFC_SW_DWN
  ws_col: WS10M

  L: 48
  H: 24
  batch_size: 32
  use_log1p: true

  extra_exo_cols:
    - T2M
    - QV2M
    - SZA
    - CLRSKY_SFC_SW_DWN
    - WD10M

  # 👇 这里改成嵌套结构，配合 utils/split.py
  splits:
    train:
      start: "2015-01-01"
      end:   "2022-12-31"
    val:
      start: "2023-01-01"
      end:   "2023-12-31"
    test:
      start: "2024-01-01"
      end:   "2024-12-31"

model:
  d_model: 256
  d_ctx: 256
  flow_layers: 6
  flow_hidden: 512

train:
  out_dir: experiments/exp_nasa_informer_flow/outputs
  epochs: 3
  lr: 0.00007
  weight_decay: 0.0001
  max_grad_norm: 1.0

  lambda_phys: 0.05
  lambda_ent: 0.05
  log_scale_target: -1.5

  seed: 42

eval:
  n_samples: 100
  temperature_base: 1.10
  temperature_slope: 0.20
